server:
  port: 8089

spring:
  application:
    name: dfs-a

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  register-with-eureka: true
  fetch-registry: true
  instance:
      prefer-ip-address: true
